### ISSUE TITLE
Peer-to-peer code review 18.02 #1

### ISSUE THREAD

**Issue by flpfar** [bertil291utn/embedding-images-video#1]
Great job, looks a lot like youtube.

-Maybe add some footer
-Try working on readme file
-Download images to load them locally (thumbnails not appearing)
-Rename app.css
-Try to use more 'em' and '%', so it will adapt better to screen sizes.

Keep the good work, guys!

**Comment by bettercallazamat** [comment]
I have not implemented footer yet and it is not in the requirements list, so I am resolving the issue without resolving feedback about the footer.
